<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Resolução da primeira prova</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 64px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h2 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h3 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h4 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h5 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h6 {
  padding-top: 69px;
  margin-top: -69px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estatística 2 - 2019/2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="prova1.html">Prova 1</a>
</li>
<li>
  <a href="prova2.html">Prova 2</a>
</li>
<li>
  <a href="tcl.html">Teorema Central do Limite</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Resolução da primeira prova</h1>

</div>


<div id="prova1" class="section level2 tabset tabset-fade">
<h2>Prova1</h2>
<hr />
<div id="questão-1" class="section level3">
<h3>Questão 1</h3>
<p>(1,0 pt) Se uma amostra com 36 observações for tomada de uma população, qual deve ser o tamanho de uma outra amostra para que o desvio padrão dessa amostra seja <span class="math inline">\(\frac{2}{3}\)</span> do desvio padrão da média da primeira?</p>
<div id="solução" class="section level4">
<h4>Solução</h4>
<p><span class="math display">\[(I)\ a_{1}: n_{1} = 36 \ \ \  \sigma_{\bar{x}_{1}} = \frac{\sigma}{\sqrt{n_{1}}} \\ (II)\ a_{2}:n_{2} = ??? \ \ \  \sigma_{\bar{x}_{2}} = \frac{\sigma}{\sqrt{n_{2}}}\]</span></p>
<p>Como o desvio padrão da segunda amostra deve ser <span class="math inline">\(\frac{2}{3}\)</span> do desvio padrão da primeira amostra temos:</p>
<p><span class="math display">\[(III)\ \sigma_{\bar{x}_{2}} = \frac{2}{3} \sigma_{\bar{x}_{1}}\]</span></p>
<p>Substituindo <strong>I</strong> e <strong>II</strong> em <strong>III</strong>:</p>
<p><span class="math display">\[\sigma_{\bar{x}_{2}} = \frac{2}{3} \sigma_{\bar{x}_{1}} \\ 
  \frac{\sigma}{\sqrt{n_{2}}} = \frac{2}{3} \frac{\sigma}{\sqrt{n_{1}}} \\
  \sqrt{n_{2}} = \sqrt{36} \frac{3}{2} \\
  n_{2} = 81
\]</span></p>
</div>
</div>
<div id="questão-2" class="section level3">
<h3>Questão 2</h3>
<p>(4,0 pts) Um auditor deseja estimar o valor médio das notas fiscais com um grande fornecedor de uma industria, de um dado ano fiscal. Para isso, fez as contas, via métodos usuais de cálculo de tamanho de amostra, que deveria tirar uma amostra de tamanho <span class="math inline">\(n = 250\)</span>. Devido a sua experiência, ele sabe que o desvio padrão é de <span class="math inline">\(\sigma = R\$ 8.600,00\)</span>. Muito curioso, ele questionou - e quero que você responda - o seguinte:</p>
<p>A. (1,0 pt) Qual a prob. de que o erro, em relação à verdadeira média, seja inferior a R$ 1.350,00 ?</p>
<p>B. (1,0 pt) Qual a probabilidade do erro ser superior a R$ 1.496,00 ?</p>
<p>C. (1,0 pt) Depois de ter respostas às duas primeiras perguntas, o gerente da indústria disse (baseado no conhecimento de anos à frente da indústria) que a média das notas fiscais é de <span class="math inline">\(\mu = R\$ 85.350,00\)</span>. Ele novamente questionou - e quero que responda - qual a probabilidade do valor médio das notas fiscais ser superior a R$ 86.250,00 ?</p>
<p>D. (1,0 pt) Se o tamanho da amostra dobrasse, a prob. da letra <strong>a</strong> aumentaria ou diminuiria ? E da letra <strong>c</strong> ?</p>
<div id="solução-1" class="section level4">
<h4>Solução</h4>
<p>Temos como dados do problema:</p>
<p><span class="math display">\[n = 250 \\
  \sigma = 8600 \\
  \sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}} = \frac{8600}{\sqrt{250}}
\]</span></p>
<p>Sabemos que:</p>
<p><span class="math display">\[E = \bar{X} - \mu \\ 
  (\bar{X} - \mu) \sim N(0, \frac{\sigma}{n})
\]</span></p>
<div id="a" class="section level5">
<h5>(A)</h5>
<p>Queremos calcular: <span class="math inline">\(P(|E|) &lt; 1350)\)</span></p>
<p><span class="math display">\[P(|E| &lt; 1350) = ...\\
  P( -1350 \frac{1}{\sigma_{\bar{x}}} &lt; Z &lt; 1350 \frac{1}{\sigma_{\bar{x}}}) = ...\\
  P(-2.48 &lt; Z &lt; 2.48) =...
\]</span></p>
<p>Calcularemos então usando o R:</p>
<pre class="r"><code>pnorm(2.48) - pnorm(-2.48)</code></pre>
<pre><code>## [1] 0.9868618</code></pre>
<p>Então temos que <span class="math inline">\(P(|E| &lt; 1350) = 0.9868618\)</span>, ou seja, aproximadamente 98.7%</p>
</div>
<div id="b" class="section level5">
<h5>(B)</h5>
<p>Queremos calcular: <span class="math inline">\(P(|E|) &gt; 1496) = P(E &gt; 1496) + P(E &lt; -1496)\)</span></p>
<p><span class="math display">\[P(E &gt; 1496) = P(Z &gt; 1496 \frac{1}{\sigma_{\bar{x}}}) = P(Z &gt; 2.75) = ...\\
  P(E &lt; -1496) = P(Z &lt; -1496 \frac{1}{\sigma_{\bar{x}}}) = P(Z &lt; -2.75) = ...\]</span></p>
<p>Calcularemos então usando o R:</p>
<pre class="r"><code>pnorm(-2.75) + (1 - pnorm(2.75))</code></pre>
<pre><code>## [1] 0.005959526</code></pre>
<p>Então temos <span class="math inline">\(P(|E|) &gt; 1496) = 0.005959526\)</span>, ou seja, aproximadamente 0.6%.</p>
</div>
<div id="c" class="section level5">
<h5>(C)</h5>
<p>Temos que: <span class="math display">\[\mu = 85350 \\
  \sigma = 8600 \\
  n = 250
\]</span></p>
<p>Queremos calcular: <span class="math inline">\(P(\bar{X} &gt; 86250)\)</span></p>
<p><span class="math display">\[P(\bar{X} &gt; 86250) = ... \\
  P(Z &gt; \frac{86250 - 85350}{\frac{8600}{\sqrt{250}}}) = ...\\
  P(Z &gt; 1.66) = ...
\]</span></p>
<p>Calcularemos então usando o R:</p>
<pre class="r"><code>1 - pnorm(1.66)</code></pre>
<pre><code>## [1] 0.04845723</code></pre>
<p>Então temos <span class="math inline">\(P(\bar{X} &gt; 86250) = 0.04845723\)</span>, ou seja, aproximadamente 4.8%.</p>
</div>
<div id="d" class="section level5">
<h5>(D)</h5>
<p>Dobrando o tamanho da amostra <span class="math inline">\(n_{2} = 2n_{1}\)</span></p>
<p>Resolvendo para a letra <strong>a</strong>:</p>
<p><span class="math display">\[P(|E| &lt; 1350) = ...\\
  P( -1350 \frac{1}{\sigma_{\bar{x}}} &lt; Z &lt; 1350 \frac{1}{\sigma_{\bar{x}}}) = ...\\
  P(-3.51 &lt; Z &lt; 3.51) =...
\]</span></p>
<p>Calcularemos então usando o R:</p>
<pre class="r"><code>pnorm(3.51) - pnorm(-3.51)</code></pre>
<pre><code>## [1] 0.9995519</code></pre>
<p>Comparando com a letra <strong>a</strong>, a probabilidade aumentou.</p>
<p>Resolvendo para a letra <strong>c</strong>:</p>
<p><span class="math display">\[P(\bar{X} &gt; 86250) = ... \\
  P(Z &gt; \frac{86250 - 85350}{\frac{8600}{\sqrt{500}}}) = ...\\
  P(Z &gt; 2.34) = ...
\]</span></p>
<p>Calcularemos então usando o R:</p>
<pre class="r"><code>1 - pnorm(2.34)</code></pre>
<pre><code>## [1] 0.00964187</code></pre>
<p>Comparando com a letra <strong>c</strong>, a probabilidade diminuiu.</p>
</div>
</div>
</div>
<div id="questão-3" class="section level3">
<h3>Questão 3</h3>
<p>(1,0 pt) O número de divórcios por indivíduo adulto casado, em certa comunidade, foi modelado pela variável aleatória <span class="math inline">\(D\)</span>, cuja função de probabilidade é apresentada a seguir. Uma amostra representada por <span class="math inline">\((D_{1}, D_{2})\)</span>, foi sorteada com dois desses indivíduos e os seguintes estimadores, para a média de divórcios, foram considerados <span class="math inline">\(\hat{\mu_{1}} = \sqrt{D_{1}D_{2}}\)</span> e <span class="math inline">\(\hat{\mu_{2}} = máximo - mínimo\)</span>. Para cada estimador, obtenha a distribuição de probabilidade e verifique se é viciado.</p>
<pre><code>##   D  X0  X1   X2   X3
## 1 p 0.5 0.4 0.05 0.05</code></pre>
<div id="solução-2" class="section level4">
<h4>Solução</h4>
</div>
</div>
<div id="questão-4" class="section level3">
<h3>Questão 4</h3>
<p>(2.5 pts) Uma amostra aleatória de 50 capacetes de corredores de motos e de automóveis foi sujeita a um teste de impacto, sendo observado algum dano em 18 desses capacetes.</p>
<p>A. (1.5 pt) Encontre um intervalo de confiança de 97% para a proporção verdadeira de capacetes desse tipo que mostraria algum dano proveniente desse teste.</p>
<p>B. (0.5 pt) Usando a estimativa <span class="math inline">\(p\)</span>, obtida a partir da amostra preliminar de 50 capacetes, quantos capacetes devem ser testados para estarmos 97% confiantes de que o erro na estimação do valor verdadeiro de <span class="math inline">\(p\)</span> seja menor do que 0,02.</p>
<p>C. (0.5 pt) Quão grande terá de ser a amostra se desejarmos estar no mínimo 97% confiantes de que o erro na estimação <span class="math inline">\(p\)</span> seja menor do que 0,02 independente do valor verdadeiro de <span class="math inline">\(p\)</span> ?</p>
<div id="solução-3" class="section level4">
<h4>Solução</h4>
</div>
</div>
<div id="questão-5" class="section level3">
<h3>Questão 5</h3>
<p>(2,5 pts) O consumo de bebidas alcoólicas por mulheres jovens maiores de idade vem aumentando no Reino Unido, nos Estados Unidos e na Europa (<em>The Wall Street Journal</em>, 15 de fevereiro de 2006). Dados (consumo anual em litros) consistentes com as descobertas relatadas no artigo do <em>The Wall Street Journal</em> são mostrados para uma amostra de 20 mulheres jovens europeias.</p>
<pre><code>##  [1] 266  82 199 174  97 164 102 113 171   0 170 222 115 130 169  93   0
## [18]  93 110 130</code></pre>
<p>Considerando que a população é aproximadamente simétrica, construa um intervalo de confiança de 96% para o consumo médio anual de bebidas alcoólicas por mulheres jovens europeias. Informação: <span class="math inline">\(\sum{X_{i}} = 2600\)</span> e <span class="math inline">\(\sum{X^2_{i}} = 419244\)</span>. Suponha que dos dados tenha distribuição aproximadamente normal.</p>
<div id="solução-4" class="section level4">
<h4>Solução</h4>
<p>São dados do problema:</p>
<p><span class="math display">\[n = 20 \ \ df = 19 \\
  \sum{x_{i}} = 2600 \ \ \sum{x_{i}^2 = 419244} 
\]</span></p>
<p>Podemos calcular então:</p>
<p><span class="math display">\[\bar{x} = \sum{\frac{x_{i}}{n}} = 130 \\
  S = 65.39
\]</span></p>
<p>Queremos um intervalo de confiança <span class="math inline">\(IC = 96\%\)</span>, para <span class="math inline">\(\alpha = 4\%\)</span> com <span class="math inline">\(df = 19\)</span> temos (lembrando que a distribuição t no R é one-tailed):</p>
<pre class="r"><code>qt(0.98, 19)</code></pre>
<pre><code>## [1] 2.204701</code></pre>
<p><span class="math display">\[t = 2.204701\]</span></p>
<p>O intervalo de confiança então é:</p>
<p><span class="math display">\[\bar{x} - t \frac{S}{\sqrt{n}} \ ; \ \bar{x} + t \frac{S}{\sqrt{n}} \\
  IC: [97.76 \ ; \ 162.24]
\]</span></p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
